### ISSUE TITLE
Странный реджект

### ISSUE THREAD

**Issue by ihsinme** [va1entei/video_stat#6]

**Comment by ihsinme** [comment]
sudo python3 insec1/ts_time1.2.py /opt/ in1/ https://files.atriw.com/mstream/zubryonline.stream/index.m3u8

**Comment by ihsinme** [comment]
sudo python3 insec1/ts_time1.2.py /opt/ in1/ https://files.atriw.com/mstream/zubryonline.stream/index.m3u8

**Comment by va1entei** [comment]
sudo rm -rf in1/20200415/192828-193834 &&sudo python3 insec1/to_repo.py /op/ in1/

**Comment by va1entei** [comment]
sudo rm -rf in1/20200415/192828-193834 &&sudo python3 insec1/to_repo.py /opt/ in1/

**Comment by va1entei** [comment]
sudo rm -rf in1/* &&echo "123" >> in/tmp && sudo python3 insec1/to_repo.py /opt/ in1/
